//auth
export const TEXT_CHANGED = 'email_changed'
export const PASSWORD_CHANGED = 'password_changed'
export const LOGIN_USER = 'login_user'
export const LOGIN_USER_SUCCESS = 'login_user_success'
export const LOGIN_USER_FAIL = 'login_user_fail'
export const SIGNUP_USER = 'signup_user'
export const SIGNUP_USER_SUCCESS = 'signup_user_success'
export const SIGNUP_USER_FAIL = 'signup_user_fail'
export const NAME_CHANGED = 'name_changed'

export const PRODUCT_UPDATE = 'product_update'
export const PRODUCT_ADD = 'product_add'
export const PRODUCT_FETCH_SUCCESS = 'product_fetch_success'
export const PRODUCT_SAVE_SUCCESS = 'product_save_success'

export const AddToCart = 'ADD_CART'
export const RemoveItemCart = 'REMOVE_CART'
export const UpdateExistingItemQuantity = 'UPDATE_EXISTING_ITEM_QUANTITY'
export const RemoveSingleItemFromCart = 'REMOVE_SINGLE_ITEM_FROM_CART'

export const CUSTOMER_UPDATE = 'customer_update'
export const CUSTOMER_ADD = 'customer_add'
export const CUSTOMER_FETCH_SUCCESS = 'customer_fetch_success'
export const TRANSACTION_ORDER_ADDED = 'transaction_order_added'
